dependencies:
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jx.34.68.246.182.nip.io
  version: 2.3.89
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jx.34.68.246.182.nip.io
  version: 2.3.89
- name: gcp-example
  repository: http://chartmuseum.jx.34.68.246.182.nip.io
  version: 1.0.19
